import SplashScreen from "./SplashScreen";
import Login from "./Login";
import Home from "./Home";
import Order from "./Order";
import Settings from "./Settings";
import Booking from "./Booking";
import MenuAll from "./MenuAll";
import Zoom from "./Zoom";
import ListBooking from "./ListBooking";
import PesanRuang from "./PesanRuang";
import EditBooking from "./EditBooking";
import Kantor from "./Kantor";
import Kandang from "./Kandang";
import ListZoom from "./ListZoom";
import PesanZoom from "./PesanZoom";
import EditZoom from "./EditZoom";
import Absen from "./Absen";
import Saran from "./Saran";
import ListHarian from "./ListHarian";
import PesanHarian from "./PesanHarian";
import EditPesanHarian from "./EditPesanHarian";

export { SplashScreen, Saran, Login, PesanZoom, Home, Order, Settings, Booking, MenuAll, Zoom, ListBooking, PesanRuang, EditBooking, Kantor, Kandang, ListZoom, EditZoom, Absen, ListHarian, PesanHarian, EditPesanHarian };
